---JUGADORES---
--1.- 
INSERT INTO JUGADORES (codigo, nombre, fechanacimiento, posicion, codigoequipo) VALUES (1, 'Iker Casillas', '5/6/80', 'Portero', 1) ;
--2.-
INSERT INTO JUGADORES (CODIGO, NOMBRE, FECHANACIMIENTO, POSICION, CODIGOEQUIPO) VALUES (2, 'Ronaldo', '7/7/84', 'Delantero', 1);
--3.-
INSERT INTO JUGADORES (CODIGO, NOMBRE, FECHANACIMIENTO, POSICION, CODIGOEQUIPO) VALUES (3, 'Zidedine Zidane', '6/6/68', 'Centrocampista', 1);
--4.-
INSERT INTO JUGADORES (CODIGO, NOMBRE, FECHANACIMIENTO, POSICION, CODIGOEQUIPO) VALUES (4, 'Samuel Etoo', '3/3/76', 'Delantero', 2);
--5.-
INSERT INTO JUGADORES (CODIGO, NOMBRE, FECHANACIMIENTO, POSICION, CODIGOEQUIPO) VALUES (5, 'Ronaldinho', '5/5/79', 'Centrocampista', 2);
--6.-
INSERT INTO JUGADORES (CODIGO, NOMBRE, FECHANACIMIENTO, POSICION, CODIGOEQUIPO) VALUES (6, 'Deco', '3/3/76', 'Centrocampista', 2);
--7.-
INSERT INTO JUGADORES (CODIGO, NOMBRE, FECHANACIMIENTO, POSICION, CODIGOEQUIPO) VALUES (7, 'Baraja', '5/5/75', 'Centrocampista', 3);
--8.-
INSERT INTO JUGADORES (CODIGO, NOMBRE, FECHANACIMIENTO, POSICION, CODIGOEQUIPO) VALUES (8, 'Albeda', '3/3/73', 'Centrocampista', 3);
--9.-
INSERT INTO JUGADORES (CODIGO, NOMBRE, FECHANACIMIENTO, POSICION, CODIGOEQUIPO) VALUES (9, 'Aimar', '5/5/75', 'Centrocampista', 3);
--10.-
INSERT INTO JUGADORES (CODIGO, NOMBRE, FECHANACIMIENTO, POSICION, CODIGOEQUIPO) VALUES (10, 'Vicente', '6/5/76', 'Centrocampista', 3);
--EQUIPOS--