CREATE TABLESPACE VUELOS
DATAFILE
  'C:\ORACLE\STARTREK\VUELOS-1.ORA' SIZE 1 M,
  'C:\ORACLE\STARTREK\VUELOS-2.ORA' SIZE 500 K
DEFAULT STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 25);

CREATE USER VUELOS 
IDENTIFIED BY VUELOS
DEFAULT TABLESPACE VUELOS
QUOTA UNLIMITED ON VUELOS;

GRANT DBA TO VUELOS;
CONN VUELOS;
