CREATE TABLESPACE VUELOS
DATAFILE
  'C:\ORACLE\STARTREK\VUELOS-1.ORA' SIZE 1 M,
  'C:\ORACLE\STARTREK\VUELOS-2.ORA' SIZE 500 K
DEFAULT STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 25);

CREATE USER VUELOS 
IDENTIFIED BY VUELOS
DEFAULT TABLESPACE VUELOS
QUOTA UNLIMITED ON VUELOS;

GRANT DBA TO VUELOS;
CONN VUELOS;
--Aeropuerto{ Nombre, direccion, telefono, director, N.º_pistas, Volumen tráfico, Ciudad_cercana}
CREATE TABLE AEROPUERTO(
NOMBRE VARCHAR2(50) NOT NULL,
DIRECCION VARCHAR2(50) NOT NULL,
TELEFONO NUMBER,
DIRECTOR VARCHAR2(20),
NUMERO_PISTAS NUMBER,
VOLUMEN_TRAFICO NUMBER,
CIUDAD_CERCANA VARCHAR2(20),
CONSTRAINT PK_AEROPUERTO PRIMARY KEY (NOMBRE)
);
COMMIT;

--Pilotos{Pasaporte, nombre, telefono, direccion, antigüedad, Horas_extra, sueldo_base}

CREATE TABLE PILOTOS(
PASAPORTE NUMBER NOT NULL,
NOMBRE VARCHAR2(20),
TELEFONO NUMBER,
DIRECCION VARCHAR2(20),
ANTIGÜEDAD VARCHAR2(20),
HORAS_EXTRA DATE,
SUELDO_BASE NUMBER,
CONSTRAINT PK_PILOTOS PRIMARY KEY (PASAPORTE),
CONSTRAINT FK_PILOTOS FOREIGN KEY (PASAPORTE) REFERENCES AEROPUERTO(NOMBRE) ON DELETE CASCADE
);
COMMIT;

--Copilotos{Pasaporte, nombre, telefono, direccion, antigüedad, Horas_extra, sueldo_base}

CREATE TABLE COPILOTOS(
PASAPORTE NUMBER NOT NULL,
NOMBRE VARCHAR2(20),
TELEFONO NUMBER,
DIRECCION VARCHAR2(20),
ANTIGÜEDAD VARCHAR2(20),
HORAS_EXTRA DATE,
SUELDO_BASE NUMBER,
CONSTRAINT PK_COPILOTOS PRIMARY KEY (PASAPORTE),
CONSTRAINT FK_COPILOTOS FOREIGN KEY (PASAPORTE) REFERENCES AEROPUERTO(NOMBRE) ON DELETE CASCADE
);
COMMIT;

--Auxilia{Fecha, Pasaporte, origen, compañía, vuelo}

CREATE TABLE AUXILIA(
FECHA DATE NOT NULL,
PASAPORTE NUMBER NOT NULL,
ORIGEN VARCHAR2(20) NOT NULL,
COMPAÑIA VARCHAR2(20) NOT NULL,
VUELO NUMBER NOT NULL,
CONSTRAINT PK_AUXILIA PRIMARY KEY (FECHA, PASAPORTE, ORIGEN, COMPAÑIA, VUELO),

);

--Auxiliares{Compañia, vuelo, origen, destino, horario, nombre}

CREATE TABLE AUXILIARES(
PASAPORTE NUMBER NOT NULL,
NOMBRE VARCHAR2(20),
TELEFONO NUMBER,
DIRECCION VARCHAR2(20),
ANTIGÜEDAD VARCHAR2(20),
HORAS_EXTRA DATE,
SUELDO_BASE NUMBER,
CONSTRAINT PK_AUXILIARES PRIMARY KEY (PASAPORTE),
CONSTRAINT FK_AUXILIARES FOREIGN KEY (PASAPORTE) REFERENCES AEROPUERTO(NOMBRE) ON DELETE CASCADE
);
COMMIT;
--Vuelos{Compañia, vuelo, origen, destino, horario, nombre}

--Pasajeros{Pasaporte, nombre}
CREATE TABLE PASAJEROS(
PASAPORTE NUMBER NOT NULL,
NOMBRE VARCHAR2(20) NOT NULL,
CONSTRAINT PK_PASAJEROS PRIMARY KEY (PASAPORTE, NOMBRE)
);
COMMIT;

CREATE TABLE VUELOS(
COMPAÑIA VARCHAR2(50) NOT NULL,
VUELO NUMBER NOT NULL,
ORIGEN VARCHAR2(20) NOT NULL,
DESTINO VARCHAR2(20),
HORARIO DATE,
NOMBRE VARCHAR2(20)
CONSTRAINT PK_VUELOS PRIMARY KEY (COMPAÑIA,VUELO, ORIGEN),
CONSTRAINT FK_VUELOS FOREIGN KEY (NOMBRE) REFERENCES AEROPUERTO(NOMBRE) ON DELETE CASCADE
CONSTRAINT 
);
COMMIT;